name: Banknotes
version: 1.6.0
description: A plugin to withdraw money and store it as a paper note
author: SainttX

main: me.sainttx.banknotes.BanknotePlugin
depend: [Vault]

commands:
  withdraw:
    description: Withdraw money as a note
    usage: |
           Withdraw money from your bank account as a note.
           /<command> [amount]
  deposit:
    description: Deposit a note
  banknotes:
    description: Reload the Banknotes plugin
    aliases: [ banknote, bn, notes, note ]
    usage: |
           Reload the Banknotes plugin.
           /<command> reload

permissions:
  banknotes.*:
    description: Gives access to all Banknotes commands
    children:
      banknotes.withdraw: true
      banknotes.deposit: true
      banknotes.reload: true
  banknotes.withdraw:
    description: Allows you to withdraw banknotes
    default: true
  banknotes.deposit:
    description: Allows you to deposit banknotes
    default: true
  banknotes.reload:
    description: Allows you to reload the plugin
    default: op